formats:
  - none
requirements_file: requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your
# docs
python:
  version: 3.7
  pip_install: true
  extra_requirements:
    - tests
    - docs
